### ISSUE TITLE
runtime: crash in split by func

### ISSUE THREAD

**Issue by tiago4orion** [NeowayLabs/nash#177]
Missing validation of value returned by function used in splitByFn.

```sh
λ> a = "hello world"
λ> fn b() { echo "oops" }
λ> c <= split($a, $b)
oops
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x53054d]

goroutine 55 [running]:
panic(0x610200, 0xc42000c160)
	/home/i4k/.gvm/gos/go1.7/src/runtime/panic.go:500 +0x1a1
github.com/NeowayLabs/nash/internal/sh.splitByFn.func1(0xc400000068, 0xb)
	/home/i4k/.gvm/pkgsets/go1.7/global/src/github.com/NeowayLabs/nash/internal/sh/split.go:162 +0x17d
strings.FieldsFunc(0xc4203e0330, 0xb, 0xc42003be90, 0xc4201043a0, 0x0, 0x0)
	/home/i4k/.gvm/gos/go1.7/src/strings/strings.go:315 +0x7a
github.com/NeowayLabs/nash/internal/sh.splitByFn(0xc4203e0330, 0xb, 0x934f60, 0xc4201b79f0, 0x0, 0x0, 0x0)
	/home/i4k/.gvm/pkgsets/go1.7/global/src/github.com/NeowayLabs/nash/internal/sh/split.go:173 +0x5f
github.com/NeowayLabs/nash/internal/sh.(*SplitFn).run(0xc420084100, 0x0, 0x0)
	/home/i4k/.gvm/pkgsets/go1.7/global/src/github.com/NeowayLabs/nash/internal/sh/split.go:58 +0x39a
github.com/NeowayLabs/nash/internal/sh.(*SplitFn).Start.func1(0xc420084100)
	/home/i4k/.gvm/pkgsets/go1.7/global/src/github.com/NeowayLabs/nash/internal/sh/split.go:77 +0x2f
created by github.com/NeowayLabs/nash/internal/sh.(*SplitFn).Start
	/home/i4k/.gvm/pkgsets/go1.7/global/src/github.com/NeowayLabs/nash/internal/sh/split.go:79 +0x75
ERROR: exit status 2
```

**Comment by tiago4orion** [comment]
almost sure this was fixed in some other PR
