### ISSUE TITLE
SIGSEGV on fn assignment

### ISSUE THREAD

**Issue by tiago4orion** [NeowayLabs/nash#80]
How to reproduce:

```sh
λ> nash
λ> fn test() { echo "hello" }
λ> hello <= test()
hello
λ> echo $hello
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x505718]

goroutine 1 [running]:
panic(0x563500, 0xc42000c150)
	/home/i4k/projects/personal/go/src/runtime/panic.go:500 +0x1a1
github.com/NeowayLabs/nash/internal/sh.(*Cmd).processArgs(0xc4201f2000, 0xc4200aeab0, 0x9, 0xc4201ce000, 0x1, 0x400, 0xc420071380, 0xc420076080, 0xc420076490, 0x0, ...)
	/home/i4k/projects/go-workspace/src/github.com/NeowayLabs/nash/internal/sh/cmd.go:85 +0xf8
github.com/NeowayLabs/nash/internal/sh.(*Cmd).SetArgs(0xc4201f2000, 0xc4201ce000, 0x1, 0x400, 0xc420071380, 0x0, 0x0)
	/home/i4k/projects/go-workspace/src/github.com/NeowayLabs/nash/internal/sh/cmd.go:102 +0x7d
github.com/NeowayLabs/nash/internal/sh.(*Shell).executeCommand(0xc420071380, 0xc4201a0320, 0x0, 0x0)
	/home/i4k/projects/go-workspace/src/github.com/NeowayLabs/nash/internal/sh/shell.go:1126 +0x36c
github.com/NeowayLabs/nash/internal/sh.(*Shell).executeNode(0xc420071380, 0x647c60, 0xc4201a0320, 0x7fb245359900, 0x0, 0xc42031ef40, 0xc420190580)
	/home/i4k/projects/go-workspace/src/github.com/NeowayLabs/nash/internal/sh/shell.go:545 +0x3a2
github.com/NeowayLabs/nash/internal/sh.(*Shell).ExecuteTree(0xc420071380, 0xc4201905a0, 0x45e994, 0xc420319110, 0x0)
	/home/i4k/projects/go-workspace/src/github.com/NeowayLabs/nash/internal/sh/shell.go:588 +0xa0
github.com/NeowayLabs/nash.(*Shell).ExecuteTree(0xc4200a2000, 0xc4201905a0, 0x0, 0x0, 0xc4201a02d0)
	/home/i4k/projects/go-workspace/src/github.com/NeowayLabs/nash/nash.go:95 +0x38
main.cli(0xc4200a2000, 0x0, 0x0)
	/home/i4k/projects/go-workspace/src/github.com/NeowayLabs/nash/cmd/nash/cli.go:130 +0xc91
main.main()
	/home/i4k/projects/go-workspace/src/github.com/NeowayLabs/nash/cmd/nash/main.go:87 +0x210
ERROR: exit status 2
```

**Comment by tiago4orion** [comment]
Fixed by other features =)

```sh
λ> fn test() { echo "hello" }
λ> hello <= test()
hello
ERROR: Invalid assignment from function that does not return values: test()
```
